---
title: test
author: Alexandra Steinhilber
date: 22-05-2025
output: 
    html_document
---

```{r}
library(dplyr)
library(ggplot2)
library(tidyr)
path<-"/home/alexandra/IDOR/data/"
```

# Données

```{r}

save_image <- function(name){
  ggsave(paste0(path,"img/",name))
}


data_phono = read.csv("/home/alexandra/IDOR/MAC_adultos_modified.csv") %>% select(-c(X)) %>%
```
```{r}
# Size of the orthographic lexicon
freq %>% ggplot(aes(x=factor(freq_min), y=taille)) +  geom_bar(stat="identity",position="dodge",fill="blue") +
  big+xlab("Minimal orthographic frequency")+ylab("Orthographic lexicon size") + ylim(0,18000)+
  geom_text(aes(label=taille), vjust=-1.5,size=20,color="black")+big
save_image("taille_lexique.png")


```

```{r}

label_oral<-c("PhonN","PhonK")
legend_oral_x<-scale_x_discrete(name="", breaks=c("False","True"), labels=label_oral)

decodage <-function(data){
  return(data %>% filter(num == 0) %>%
           group_by(context_sem,oral,freq) %>%
           summarise(mean = mean(success)))}

decodage_plot <-function(data){
  return(data %>% mutate(OLS=factor(size)) %>%
           ggplot(aes(x=oral, y=mean, fill=OLS)) +
           bar + grid_context + big + ylab("Reading Accuracy") + xlab("") +
            labs(alpha = "OLS")+legend_oral_x+
            scale_fill_viridis_d(option = "G")
           )
           }

dec <-data_taille_lexique  %>% decodage()
dec <- merge(dec, freq, by = "freq", all.x = TRUE)

plot <-dec  %>% decodage_plot()
save_image("taille_lexique_decodage.png")

diff <- dec %>% pivot_wider( names_from = context_sem, values_from = mean, names_prefix = "context_" ) %>%
  mutate(difference = context_True - context_False)
plot_diff <- diff %>% mutate(OLS=factor(size)) %>%
  ggplot(aes(x=oral, y=difference, fill=OLS)) + bar +
  big + ylab("Reading Accuracy improvement") +
  xlab(" ") + legend_oral_x +
  scale_fill_viridis_d(option = "G")
save_image("OLS_context.png")

## Stats
library(lme4)

data_stat <- data_taille_lexique %>% filter(num==0) #%>% within(type <- relevel(type, ref = "random"))

# modèle général
summary(glm(success ~ context_sem * oral * freq , data=data_stat, family=binomial(link="logit")))





```
